### ISSUE TITLE
Questions about benchmark result and performance

### ISSUE THREAD

**Issue by UMRnInside** [openfans-community-offical/Debian-Pi-Aarch64#1]
As far as I know, there are some differences that might **affect benchmark result** :

| ...              | RPi-arm64            | Debian-Pi-Aarch64 |
|------------|---------------------|----------------------|
|Hardware | Pi 3B rev 1.2 | Pi 3B/3B+ ? |
| Kernel      | 4.14.?? (older)     | 4.14.90   |
|Filesystem| btrfs | f2fs/btrfs/ext4 ? |
| CPU Frequency | 1.2 GHz | ? |
|CPU Schedule | conservative | ? |
| Swap | None | zSWAP |
| Boot | legacy bootcode.bin | UEFI |

So I wonder how to improve performance and benchmak result.

********
所以，怎样在基准测试中取得好成绩呢？

**Comment by aiminickwong** [comment]
@UMRnInside 
We have said that is an **incomplete testing**, we used 3B+ , another way, ext4 is much better than btrfs. It is necessary to open swap. There are still some gaps between EFI mode and non-EFI, do most changes were kernel  caches mechanism and the file system I/O code.
so many different: kernel ver., system very., different kernel and conf, even about the TF card hardware performance , it's a result of a combined factor.
