### ISSUE TITLE
关于3B+ wifi的问题（不知道是否是个例）

### ISSUE THREAD

**Issue by tiandi398** [openfans-community-offical/Debian-Pi-Aarch64#10]
刷写2019-02-24-OPENFANS-Debian-Stretch-Desktop-Aarch64-ext4-v2019-1.0-U8.img，这个版本，一切都安装就绪，连接wifi也能正常链接，然后，过一两分钟，wifi就断开链接了，显示设备未就绪，之后再重启也没用，插有线可以一直正常工作

**Comment by aiminickwong** [comment]
@tiandi398  请检查你的无线设置，使用networkmanager客户端，已知WICD客户端存在部分兼容问题

**Comment by tiandi398** [comment]
> @tiandi398 请检查你的无线设置，使用networkmanager客户端，已知WICD客户端存在部分兼容问题

我试验了，这个客户端似乎也不起作用，不管选择打开WiFi、还是关闭，还是输入了密码，都不起作用，我觉得可能是我这个3b+的毛病

**Comment by aiminickwong** [comment]
目前暂时未收到同样的为反馈，暂时关闭这个问题。
