### ISSUE TITLE
how to install sdl_config in BaseOS Plus++

### ISSUE THREAD

**Issue by longbozhan** [openfans-community-offical/Debian-Pi-Aarch64#101]
my os system is BaseOS Plus++, but when I run  pip3 install pygame  pygame, I got the error:
Collecting pygame
  Using cached https://files.pythonhosted.org/packages/0f/9c/78626be04e193c0624842090fe5555b3805c050dfaa81c8094d6441db2be/pygame-1.9.6.tar.gz
    Complete output from command python setup.py egg_info:
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: pkg-config: not found
    /bin/sh: 1: pkg-config: not found
    /bin/sh: 1: pkg-config: not found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    
    Hunting dependencies...
    WARNING: "sdl-config" failed!
    WARNING: "pkg-config freetype2" failed!
    WARNING: "freetype-config" failed!
    Unable to run "sdl-config". Please make sure a development version of SDL is installed.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-1dqdstuo/pygame/

I run apt-get install sld-config, but fail. I guess I was using a none desktop version so that I can not install sdl-config, any suggetion?

**Comment by aiminickwong** [comment]
No feedback for a long time, close the question, welcome to update and ask to open at any time. :)
