### ISSUE TITLE
Where can I install the corresponding header package for the kernel?

### ISSUE THREAD

**Issue by hughjfchen** [openfans-community-offical/Debian-Pi-Aarch64#102]
The installed kernel version is 4.9.88, however, I can't find the corresponding headers package for this kernel version, hence I can't install DKMS kernel module. Where is the header package?

**Comment by dony71** [comment]
same question
install "sudo apt-get install raspberrypi-kernel-headers" but not availble

**Comment by hughjfchen** [comment]
Well, I can't figure out how to fix that yet, hence I switch back to raspbian with the 64-bit kernel.

**Comment by dony71** [comment]
> Well, I can't figure out how to fix that yet, hence I switch back to raspbian with the 64-bit kernel.

where do you get raspbian arm64 image?

**Comment by hughjfchen** [comment]
> > Well, I can't figure out how to fix that yet, hence I switch back to raspbian with the 64-bit kernel.
> 
> where do you get raspbian arm64 image?

Actually, it a raspbian 32-bit user-land with a 64-bit kernel and a 64-bit deiban within a nspaw container. Sokaki- has a repo which you can download such an image from: https://github.com/sakaki-/raspbian-nspawn-64

**Comment by yi-ge** [comment]
I have the same question...

**Comment by PHCSJC** [comment]
Same problem.
How install kernel headers?

**Comment by aiminickwong** [comment]
Down load rpi officical  source code.

**Comment by IS2511** [comment]
Doesn't really explain much...There are no source files in /lib/modules/kernel_version_here/build, how do I build a kernel module?
