### ISSUE TITLE
the Deepin Appstore doesn't work

### ISSUE THREAD

**Issue by geol** [openfans-community-offical/Debian-Pi-Aarch64#103]
It shows up network error.
And the build-in apt source.list didn't work neither. The url **http://enterprise.packages.deepin.com/** is unreachable. It has worked since I removed _enterprise._ from the url. But the Deepin Appstore still not working after I did this.
打开深度商店时总是显示“网络错误”。
自带的apt软件源似乎是有问题的，不过后来我把软件源地址改为**http://packages.deepin.com**（去掉enterprise）就可以正常操作了。但是深度商店还是“网络错误”。

**Comment by aiminickwong** [comment]
deepin store had stoped for arm.
