### ISSUE TITLE
can't using imshow() function of opencv

### ISSUE THREAD

**Issue by o0olele** [openfans-community-offical/Debian-Pi-Aarch64#108]
opencv: cross-compile( gtk2.0)
when trying use `imshow()`, the opencv lib get a error: 
~~~shell
what():  OpenCV(4.0.1) /home/opencv-4.0.1/modules/highgui/src/window.cpp:627: error: \
(-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, \
GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and \
pkg-config, then re-run cmake or configure script in function 'cvShowImage'
~~~  

should i install the gtk2.0 on aarch64?
----------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------
but i tried build opencv lib on aarch64 before
after install some dependencies:
~~~
sid-uesd sudo apt-get install libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
~~~
and reboot
the system crashed(in boot), and show:
~~~
A start job is running for hold until boot process finishes up
~~~

**Comment by aiminickwong** [comment]
New edition ,fix the lib relationship
