### ISSUE TITLE
xfce desktop does not start

### ISSUE THREAD

**Issue by kppomzh** [openfans-community-offical/Debian-Pi-Aarch64#113]
Every time after running init 5, the startup circle flashed a moment, then returned to the command line interface again.
I didn't modify the settings file of xfce, just modified the wallpaper and theme.

**Comment by kppomzh** [comment]
ah,I rename the user pi

**Comment by aiminickwong** [comment]
Log or msg PLS.

**Comment by aiminickwong** [comment]
Do not change user pi, the desktop is running under pi user
