### ISSUE TITLE
Can't enter multi-user mode after thrust USB driver

### ISSUE THREAD

**Issue by kppomzh** [openfans-community-offical/Debian-Pi-Aarch64#114]
this USB driver has not register in /etc/fstab,but when I thrust it on my pi,Debian can't normally enter "init 5" mode.

**Comment by kppomzh** [comment]
I carefully checked the information of systemctl and found a kernel log, prompting "usb 1-1.4.4: device descriptor read / 64, error -32".
I think this is probably why it can't be started.
My USB driver is Lexar S47. 
If I use ASM's SATA to USB converter chip to insert a mobile hard disk, it will start normally.

**Comment by kppomzh** [comment]
Majaro/Raspbian don't have this problem.
Also I build the newset kernel (5.6.y),it still didn't work.

**Comment by aiminickwong** [comment]
Pls try to use New version.
