### ISSUE TITLE
unable to load kernel module: "configs"

### ISSUE THREAD

**Issue by goodliving** [openfans-community-offical/Debian-Pi-Aarch64#115]
I want to run kubernetes on this system, but failed。

kubeadm init --config config.yml
[ERROR SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/4.19.85-OPENFANS+20191125-v8\n"

I NEED SOME HELP, THANKS

**Comment by goodliving** [comment]
System Info：4.19.85-OPENFANS+20191125-v8

**Comment by aiminickwong** [comment]
We hadn't support load kernel configs module yet.
