### ISSUE TITLE
Can add Sogou Pinyin? 可以添加搜狗拼音吗？

### ISSUE THREAD

**Issue by laomocode** [openfans-community-offical/Debian-Pi-Aarch64#116]
# English:
Chinese Kylin OS's source have Sogou Pinyin arm64 version,Can add Sogou Pinyin in new system image?
Download Link:http://archive.kylinos.cn/kylin/KYLIN-ALL/pool/main/s/sogoupinyin/sogoupinyin_2.3.1.0110kord1k83_arm64.deb
# Chinese:
国内的银河麒麟的源有搜狗拼音的arm64版本，请问是否能在新的版本添加输入法？
下载链接：http://archive.kylinos.cn/kylin/KYLIN-ALL/pool/main/s/sogoupinyin/sogoupinyin_2.3.1.0110kord1k83_arm64.deb

**Comment by mylovesaber** [comment]
sunpinyin or rime is ok.

**Comment by aiminickwong** [comment]
You can install by yourself, thanks for suggestion.
