### ISSUE TITLE
RASPBERRY PI 4 OTG can't run

### ISSUE THREAD

**Issue by yi-ge** [openfans-community-offical/Debian-Pi-Aarch64#118]
Raspberry Pi 4 can do USB OTG via the USB-C connector (according to this [answer](https://dev.webonomic.nl/4-ways-to-connect-your-raspberry-pi-4-to-the-internet)) - but in the system, i can't connect USB enternet.

Run `config -a` show:
```
root@raspbian:~# ifconfig -a usb0
usb0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 2e:2c:b3:27:95:39  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Can't find USB enternet in the MacOS or Windows 10 system(with driver).

Maybe because of `/boot/cmdline.txt` or Linux Kernel.

Thank you.

**Comment by aiminickwong** [comment]
Very sorry, we hadn't any usb hardware as your's , cannot make any testing.
