### ISSUE TITLE
no gpu vc4 support for plus++ version. 关于plus++版本gpu驱动的问题（没有支持硬件加速）

### ISSUE THREAD

**Issue by Xixi20160512** [openfans-community-offical/Debian-Pi-Aarch64#120]
首先，感谢开发者的付出！！

Thanks for all your efforts!!

## The version I currently use：
 “2019-12-30-OPENFANS-Debian-Buster-Aarch64-ext4-v2019-2.0-U2-Release-plus++.img.xz”
## Problems
when i install xcfe desktop myself and try to get current gpu driverinfo, i get this:
![image](https://user-images.githubusercontent.com/19320239/82045889-718c0b00-96e2-11ea-8d7a-b8987470b7c4.png)
As you can see, the device is`llvmpipe`,not `video core` which is shown like bellow
![image](https://github.com/openfans-community-offical/Debian-Pi-Aarch64/blob/bcf3755c5bdb04c62d77e409c71d3f2b3e3cdc35/images/deepin_info.png?raw=true)
## Expect

1. can I change current render dervie to vc4?

**Comment by aiminickwong** [comment]
plus++ version not support, please use our desktop edition : Desktop Full-Featured version.
