### ISSUE TITLE
A question about static ip address

### ISSUE THREAD

**Issue by Sunhill666** [openfans-community-offical/Debian-Pi-Aarch64#123]
I want to use the static ip address, Is this configuration right?

`\# interfaces(5) file used by ifup(8) and ifdown(8)
\# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d
\#\# Used dhcp ip address set eth0 inet to dhcp,
\#\# or used static ip address set eth0 to static
\#\# and change other ip settings.
\#\# If you wanna let settings to take effect,
\#\# uncomment symbol in front.

\#auto eth0
\#allow-hotplug eth0

\#iface eth0 inet dhcp
iface eth0 inet static
address 192.168.123.77
netmask 255.255.255.0
gateway 192.168.123.1
dns-nameservers 114.114.114.114 223.5.5.5
`

**Comment by aiminickwong** [comment]
#auto eth0
You should Uncommit this line.
