### ISSUE TITLE
Can I use icloud cloud disk to help the project to split downloads?

### ISSUE THREAD

**Issue by zhaokelei** [openfans-community-offical/Debian-Pi-Aarch64#125]
I found that icloud cloud disk can be downloaded quickly, and can be downloaded in different ways, including for Chinese users.

**Comment by aiminickwong** [comment]
Share for everyone, anyway, anywhere, enjoy! @zhaokelei

**Comment by zhaokelei** [comment]
https://www.icloud.com/iclouddrive/0XCOHNaasFSYZRD9-rZhjCbNw#2020-06-15-OPENFANS-Debian-Buster-Aarch64-ext4-v2019-2.0-U3-Release

https://www.icloud.com/iclouddrive/0ajjHJCKj5UX2kcK2YVyhqlSw#2020-06-15-OPENFANS-Debian-Buster-Aarch64-ext4-v2019-2.0-U3-Release-plus

https://www.icloud.com/iclouddrive/0OcmvFXI2MsUB6j5mFu3w-pEQ#2020-06-15-OPENFANS-Debian-Buster-Desktop-Aarch64-ext4-v2019-2.0-U3-Release

**Comment by zhaokelei** [comment]
I put three versions of the image file diffluence address here, which can be downloaded at any time.

**Comment by aiminickwong** [comment]
@zhaokelei You can change and upload the newest desktop edition 2020-06-16-U3 , thank you.

**Comment by zhaokelei** [comment]
好的

**Comment by aiminickwong** [comment]
@zhaokelei 20200617 be comming...  :)

**Comment by zhaokelei** [comment]
> @zhaokelei 20200617 be comming... :)

Updated

**Comment by aiminickwong** [comment]
@zhaokelei 
TKY for Sharing! :)

**Comment by aiminickwong** [comment]
@zhaokelei 20200622 Had upgrade for all IMGs
