### ISSUE TITLE
Update Python to higher version Or 3.6.8 in Debian-Buster-v2019-2.0-U3.img

### ISSUE THREAD

**Issue by patrickj-fd** [openfans-community-offical/Debian-Pi-Aarch64#127]
Because of Asyncio BUG in python 3.7.3, can you update to higher version Or 3.6.8 in '2020-06-15-OPENFANS-Debian-Buster-Aarch64-ext4-v2019-2.0-U3-Release.img'

**Comment by aiminickwong** [comment]
The pkg's version was the same as debian buster upstream, we will not change the default version by ourself,  the python if U wanna change the version, the best suggestion is use **python virtualenv** , U can change the version which U want and defined by YOURSELF.
