### ISSUE TITLE
ifconfig command not found

### ISSUE THREAD

**Issue by zerorooot** [openfans-community-offical/Debian-Pi-Aarch64#13]
需要自行设置
vi ~/.bashrc
export PATH=$PATH:/sbin
source ~/.bashrc
后才能使用
版本：2019-06-02-OPENFANS-Deepin-Professional-Desktop-Aarch64-ext4-v2019-1.0-U9.img

**Comment by aiminickwong** [comment]
ifconfig 属于超级用户的命令，在sbin下，需要切换到root账户下才能使用，默认的pi不是管理员，只是有执行sudo的权限，此为系统默认值，不是问题，所以将关闭这个问题。 @zerorooot
