### ISSUE TITLE
Realtime kernel

### ISSUE THREAD

**Issue by DAlam6er** [openfans-community-offical/Debian-Pi-Aarch64#130]
Hello. I tried to patch kernel 5.4.47 with the rt-patch from here /pub/linux/kernel/projects/rt/5.4/ for using my Raspberry as a musical center. But on the config stage I still can't find "Fully Preemptible Kernel" in the Preemption Model section.

**Comment by aiminickwong** [comment]
It's not the kernel which was build by ours.
