### ISSUE TITLE
mysql-docker problem

### ISSUE THREAD

**Issue by tiantian1412** [openfans-community-offical/Debian-Pi-Aarch64#132]
when use  docker, and pull mysql image, appear problems as follow:

latest: Pulling from library/mysql
latest: Pulling from library/mysql
no matching manifest for linux/arm64/v8 in the manifest list entries

why do this happens and how can I handle it?

**Comment by SpicaLab** [comment]
MySQL 的docker官方镜像只支持X86平台，建议用mariadb
https://hub.docker.com/_/mariadb

MySQL作者搞得，兼容性很好

**Comment by sunht6** [comment]
docker pull mysql/mysql-server
