### ISSUE TITLE
如何开启硬件串口，并修改映射关系？

### ISSUE THREAD

**Issue by wanggao1990** [openfans-community-offical/Debian-Pi-Aarch64#135]
在官方系统中可以使用 raspi-config中可以开启 /dev/serial0， 并可以修改映射到 ttyAMA0。
这个系统该如何操作？

**Comment by aiminickwong** [comment]
Debian-Pi-Aarch64 was not support **raspi-config** command, U'd better edit the config.txt, U can find the readme at rpi official site to check the official documents.
