### ISSUE TITLE
Changing language from Chinese to English

### ISSUE THREAD

**Issue by kyroninja** [openfans-community-offical/Debian-Pi-Aarch64#137]
I suggest adding a section to the readme for your english speaking users. When I installed openfans everything is in Chinese. It took a while to revert to English language. Here is what I did to get the system into English.

$ sudo dpkg-reconfigure locales
select en_US.UTF-8 to be generated and the same for the default language.

Open /home/pi/.xsessionrc and comment out the export LANG variables for Chinese language.

Reboot system and interface/apps should be in English

**Comment by aiminickwong** [comment]
In Full Desktop Version change file "/home/pi/.xsessionrc"
