### ISSUE TITLE
build the k8s master node failed

### ISSUE THREAD

**Issue by hua1010** [openfans-community-offical/Debian-Pi-Aarch64#138]
I need to do a k8s cluster training, but I found that there are some problems with the master node construction. 
Maybe the kernel version is too high or the necessary modules are not insmod. 
Compared with the official raspberry, it is found that it is normal. 
The following is an failed log:
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/5.4.47-OPENFANS+20200622-v8\n", err: exit status 1

Hope to get your help,thx

**Comment by NJ2046** [comment]
the same to you

**Comment by hua1010** [comment]
you can use the official image, good luck

**Comment by NJ2046** [comment]
thk

**Comment by aiminickwong** [comment]
We're not support configs modules, the better way is change the you deploy scripts
