### ISSUE TITLE
在x86上 通过qemu 模拟问题

### ISSUE THREAD

**Issue by liangtiansheng** [openfans-community-offical/Debian-Pi-Aarch64#14]
首先感谢您的奉献，我用arm64的飞腾服务器和通过x86 qemu模拟都无法启动这里的系统，是否只适用树莓派

**Comment by aiminickwong** [comment]
如果您需要模拟的话，只需要使用rootfs分区即可，请使用您自己的内核文件引导，这可能会失去一些特性，系统镜像的内核文件不兼容qemu，

**Comment by aiminickwong** [comment]
此问题已结束，关闭。
