### ISSUE TITLE
Ask for help to find out the source code

### ISSUE THREAD

**Issue by hyphantom** [openfans-community-offical/Debian-Pi-Aarch64#143]
root       601     1  0 20:14 ?        00:00:00 /sbin/wpa_supplicant -u -s -O /run/wpa_supplicant
root       728     1  0 20:14 ?        00:00:00 wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant.conf -iwlan0 -Dnl80211,wext
how to find the starter demand

**Comment by hyphantom** [comment]
miracle-wifid &  log：
ERROR: supplicant: wpas (pid:32534) failed unexpectedly, relaunching after short grace period.. (supplicant_failed() in ../../../src/wifi/wifid-supplicant.c:2331)
ERROR: supplicant: wpas (pid:32547) failed unexpectedly, relaunching after short grace period.. (supplicant_failed() in ../../../src/wifi/wifid-supplicant.c:2331)
ERROR: supplicant: wpas (pid:32548) failed again.. entering grace period, waiting 30s before relaunching (supplicant_failed() in ../../../src/wifi/wifid-supplicant.c:2335)

**Comment by aiminickwong** [comment]
What's your means?

**Comment by hyphantom** [comment]
> What's your means?

Try to use miraclecast as the client in the desktop version to initiate streaming to the TV .
尝试在桌面版中，使用miraclecast作为客户端，向电视发起串流

**Comment by aiminickwong** [comment]
Can't you tell us you steps, pls
