### ISSUE TITLE
I can't download the system image from HUAWEI OSS STORAGE.

### ISSUE THREAD

**Issue by Xuyiyang23333** [openfans-community-offical/Debian-Pi-Aarch64#149]
https://pifan.cn.obs.cn-north-1.myhuaweicloud.com/

![Screenshot_20201016_142016.png](https://i.loli.net/2020/10/16/eQtudPGxTJaimFs.png)

**Comment by 52885199** [comment]
I meet this issues too
![image](https://user-images.githubusercontent.com/48471092/97259644-43485500-1856-11eb-9ecb-8806062fadd4.png)

**Comment by aiminickwong** [comment]
We are not support to download images fromm OBS now.
