### ISSUE TITLE
Make file it report a issue 

### ISSUE THREAD

**Issue by elohffa** [openfans-community-offical/Debian-Pi-Aarch64#150]
When I use the make my usb driver ( exar-uart-driver) 
It report a error message 
make -C /lib/modules/5.4.47-OPENFANS+20200622-v8/build M=/home/pi/exar-uart-driver
make[1]: *** /lib/modules/5.4.47-OPENFANS+20200622-v8/build: 没有那个文件或目录。 停止。
make: *** [Makefile:9：all] 错误 2

**Comment by aiminickwong** [comment]
The **build** is Kernel source directory, you can change it and used rpi official source from github.
