### ISSUE TITLE
希望能添加对respeaker/seeed-voicecard的支持

### ISSUE THREAD

**Issue by HenryJi529** [openfans-community-offical/Debian-Pi-Aarch64#153]
[seeed-voicecard](https://github.com/respeaker/seeed-voicecard)
<img width="838" alt="98325137-0d128e80-2029-11eb-99c4-b327f5378f0d-2" src="https://user-images.githubusercontent.com/41288155/99500047-bb68ed00-29b4-11eb-9dc7-15f8ebf4d011.png">

**Comment by aiminickwong** [comment]
In ver. U6:

```
modprobe kheaders
```

U'll see headers tar file at:

```
/sys/kernel/kheaders.tar.xz
```
