### ISSUE TITLE
How to install kernel-headers

### ISSUE THREAD

**Issue by wojiuchigua** [openfans-community-offical/Debian-Pi-Aarch64#160]
I want to use some programs but they need to use kernel-headers, use apt install kernel-headers and sudo apt install raspberrypi-kernel-headers
Invalid.

**Comment by aiminickwong** [comment]
In ver. U6:

```
modprobe kheaders
```

U'll see headers tar file at:

```
/sys/kernel/kheaders.tar.xz
```

**Comment by liurenqiu520** [comment]
`
pi@raspbian:~$ sudo modprobe kheaders
`
`
modprobe: FATAL: Module kheaders not found in directory /lib/modules/5.4.83-OPENFANS+20210102-v8
`

**Comment by aiminickwong** [comment]
@liurenqiu520 try newest kernel upkg.
