### ISSUE TITLE
Ask for  the recommended memory size for Pi 4b

### ISSUE THREAD

**Issue by Mart11n** [openfans-community-offical/Debian-Pi-Aarch64#168]
I installed Ubuntu-20.04.1-Server-ARM64 on my Raspberry Pi and found that it took up 1G of memory after booting, but my Raspberry Pi only had 2G of memory. I would like to know how much memory debian-pi-aarch64 will take up and what's the recommended memory size required for different versions of Debian-Pi-Aarch64?

**Comment by aiminickwong** [comment]
Except **Full Desktop Version** of Debian-Pi-Aarch6 , we suggest to used mem >= 2G, other editions just >=1G will be ok.

**Comment by aiminickwong** [comment]
Better experience,  mem> = 2G is better.
