### ISSUE TITLE
how to set up Chinese?

### ISSUE THREAD

**Issue by whtry** [openfans-community-offical/Debian-Pi-Aarch64#169]

**Comment by whtry** [comment]
when i used ssh to connect my raspberrypi3B,it showed English,but in web,it showed Chinese
![image](https://user-images.githubusercontent.com/69187424/106384365-770eba00-6405-11eb-871b-0689c0c5cd63.png)
![image](https://user-images.githubusercontent.com/69187424/106384385-8db51100-6405-11eb-89b2-99dd1ef54ab8.png)

**Comment by whtry** [comment]
it is very strange...

**Comment by whtry** [comment]
it is very strange...

**Comment by aiminickwong** [comment]
export the Global ENV  **LANG** in your console or user's bash.
