### ISSUE TITLE
ping： network is unreachable 

### ISSUE THREAD

**Issue by hclasmn** [openfans-community-offical/Debian-Pi-Aarch64#171]
![PH6A5U3PJCEX0YV(AHFLMHP](https://user-images.githubusercontent.com/32213103/107760845-60515700-6d65-11eb-8c56-6db1e043b743.jpg)
![}GYQ``F))B~YM}~`E(QK{~H](https://user-images.githubusercontent.com/32213103/107760851-621b1a80-6d65-11eb-9d56-af07e7bf688c.jpg)

It happens every two days。

**Comment by aiminickwong** [comment]
Your nic wlan0 hadn't any ip addr, the network is unreachable, check you router or network device DHCP pool time range or other settings.

**Comment by hclasmn** [comment]
> Your nic wlan0 hadn't any ip addr, the network is unreachable, check you router or network device DHCP pool time range or other settings.


Used normally all the time。

Restart and return to normal when it happened
