### ISSUE TITLE
Gitee LOCKED

### ISSUE THREAD

**Issue by 123ABCDF11345** [openfans-community-offical/Debian-Pi-Aarch64#172]
gitee已封禁[readme_zh.md](https://gitee.com/openfans-community/Debian-Pi-Aarch64/blob/master/README_zh.md),显示根据相关法律法规内容不予以展示

**Comment by aiminickwong** [comment]
We're checking now.

**Comment by aiminickwong** [comment]
It's already works now. @123ABCDF11345
