### ISSUE TITLE
ufw not work

### ISSUE THREAD

**Issue by Vastzhang97** [openfans-community-offical/Debian-Pi-Aarch64#175]
Hi，my pi4b iso is 2021-01-03-OPENFANS-Debian-Buster-Aarch64-ext4-v2021-2.0-U6-Release-plus++.img.xz,I install ufw for it and ufw deny 81,but i can still access my application on port 81,what wrongs?

[![6JCVds.png](https://s3.ax1x.com/2021/03/10/6JCVds.png)](https://imgtu.com/i/6JCVds)

[![6J9yGV.png](https://s3.ax1x.com/2021/03/10/6J9yGV.png)](https://imgtu.com/i/6J9yGV)

**Comment by aiminickwong** [comment]
we used iptables, not ufw.

**Comment by Vastzhang97** [comment]
> we used iptables, not ufw.

Ok,iptables work.There are plans to support UFW in the future？

**Comment by Vastzhang97** [comment]
I find the problem.Ufw is not work with docker container by default,you slove it do as [follow](https://www.techrepublic.com/article/how-to-fix-the-docker-and-ufw-security-flaw/)
