### ISSUE TITLE
最新版本U6的

### ISSUE THREAD

**Issue by SonnTakuu** [openfans-community-offical/Debian-Pi-Aarch64#176]
树莓派4B
蓝牙输出正常没问题，但是有线是单声道。
另外，请问如何在上面运行Windows x86的软件呢
基地的系统自带mpv，安装jellyfin-deskop以后居然可以硬借hevc了，接双屏办公也很不错。真的是很感谢。一下子树莓派就有了上网本的感觉了（还是可以双屏硬解HEVC的）

**Comment by SonnTakuu** [comment]
另外，像说明那样的Android软件如何运行呢？linux不支持onenote，第三方客户端不支持arm64。

**Comment by hmsjy2017** [comment]
可以使用 QEMU 模拟 Windows 10 ARM64，然后运行 x86 软件。
至于 Android 软件，可以通过 Anbox 运行。

**Comment by SonnTakuu** [comment]
HDMI和3.5输出均只能输出单声道怎么办，是哪里设置的不对吗？

**Comment by SonnTakuu** [comment]
好像没有QEMU和Anbox的安装针对树莓派4的教程，可以指导一下吗。

**Comment by hmsjy2017** [comment]
安装 Windows 10 有两种方式：
- 实机安装：[树莓派4b安装Win10 ARM](https://www.bilibili.com/read/cv7745562/)
性能损耗小，部署简单，但 Wi-Fi 无驱动，可以用以太网来代替
- 虚拟机安装
  + [树莓派完美运行win10 arm「满足你的日常需求](https://blog.csdn.net/qq_41676577/article/details/112974605)（树莓派爱好者基地官方的教程，安装较简单）
视频：https://www.bilibili.com/video/av884150344
  + [树莓派通过KVM安装Win10 Arm64系统](https://talk.quwj.com/topic/1818)（另一个视频，安装较为复杂，但可定制度高）

无论是哪种方式，都不能使用 3D 加速。

基地的系统暂时不能运行 Android 软件，官方说未来会支持。目前可以通过 Anbox 实现运行 Android 软件，但只能安装arm64-v8a的应用。
[Anbox在ARM64架构Linux上运行Android程序](https://talk.quwj.com/topic/2205)
安装过程较为繁琐。

**Comment by SonnTakuu** [comment]
基地系统声卡输出单声道如何解决呢，使用本系统以后居然可以流畅播放MA10P视频不卡了，但可惜声卡不知道如何调整为双声道；要是这个解决了，这个系统真的让树莓派无敌了。

iPhoneから送信

2021/04/14 23:25、Tony ***@***.***>のメール:

﻿

安装 Windows 10 有两种方式：

  *   实机安装：树莓派4b安装Win10 ARM<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.bilibili.com%2Fread%2Fcv7745562%2F&data=04%7C01%7C%7C461cb62fbd1f460e51f008d8ff598621%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540107251510986%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9O4Tg3oC4ZvEfb4g5l%2B%2BRFM%2FMdTxKse5%2BUIqW7RCysI%3D&reserved=0>
性能损耗小，部署简单，但 Wi-Fi 无驱动，可以用以太网来代替
  *   虚拟机安装
     *   树莓派完美运行win10 arm「满足你的日常需求<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fblog.csdn.net%2Fqq_41676577%2Farticle%2Fdetails%2F112974605&data=04%7C01%7C%7C461cb62fbd1f460e51f008d8ff598621%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540107251510986%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dA%2F5iVEQy5KIAEyWIjreXGlZjVWiTEpuxv2543UDWN0%3D&reserved=0>（树莓派爱好者基地官方的教程，安装较简单）
视频：https://www.bilibili.com/video/av884150344<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.bilibili.com%2Fvideo%2Fav884150344&data=04%7C01%7C%7C461cb62fbd1f460e51f008d8ff598621%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540107251520943%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BkQsteDCmlae7j3P7MMQsx10T9sDAczgoZI4two1c8c%3D&reserved=0>
     *   树莓派通过KVM安装Win10 Arm64系统<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftalk.quwj.com%2Ftopic%2F1818&data=04%7C01%7C%7C461cb62fbd1f460e51f008d8ff598621%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540107251520943%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FH1HxMqdnJQ9rRxnrWrl2sRi3dzQ9dV67kOtY2TxeIw%3D&reserved=0>（另一个视频，安装较为复杂，但可定制度高）

无论是哪种方式，都不能使用 3D 加速。

基地的系统暂时不能运行 Android 软件，官方说未来会支持。目前可以通过 Anbox 实现运行 Android 软件，但只能安装arm64-v8a的应用。
Anbox在ARM64架构Linux上运行Android程序<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftalk.quwj.com%2Ftopic%2F2205&data=04%7C01%7C%7C461cb62fbd1f460e51f008d8ff598621%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540107251530895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IEFt4DoLz4hsH%2BOnGIfWTiBZQa0hcEw8FKoARp%2Bfv9g%3D&reserved=0>
安装过程较为繁琐。

**Comment by SonnTakuu** [comment]
呃，我询问的是openfans树莓派爱好者基地的64位debian系统，无论是HDMI还是3.5在设置中都只有单声道可选。

iPhoneから送信

2021/04/14 23:34、Tony ***@***.***>のメール:

﻿

我只用树莓派官方系统，没有这个问题。

**Comment by hmsjy2017** [comment]
我不是树莓派基地的官方人员，不是很了解。你可以在他们的 QQ 群里面提问。

**Comment by SonnTakuu** [comment]
哦哦，谢谢了，
以前在群里问过，好像没有人给出方案。


iPhoneから送信

2021/04/14 23:38、Tony ***@***.***>のメール:

﻿

我不是树莓派基地的官方人员，不是很了解。你可以在他们的 QQ 群里面提问。

**Comment by hmsjy2017** [comment]
如果要运行 Android 应用，用 [Lineage OS](https://konstakang.com/devices/rpi4/) 体验可能会更好一些。唯一缺点是无法硬解视频。

**Comment by hmsjy2017** [comment]
你可以在[趣小组](https://talk.quwj.com/)提问，也许有人会给出回答。

**Comment by SonnTakuu** [comment]
是啊，无法硬解就很淦。。
我有一个nas，有安装jellyfin服务，jellyfin-mpv客户端是开源项目，但只有基地系统因为自带mpv所以可以硬解播放MA10p。
超频以后网页也基本没问题，平时学习用的anki居然也有linux版本，所以如果声音问题能解决就可以代替我98%的台式机用途。
如果虚拟的win10arm可以跑跑galgame那就可以代替99%了。瞬间树莓派就不吃灰了。

iPhoneから送信

2021/04/14 23:42、Tony ***@***.***>のメール:

﻿

如果要运行 Android 应用，用 Lineage OS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fkonstakang.com%2Fdevices%2Frpi4%2F&data=04%7C01%7C%7C8539f2629f9a4540564108d8ff5bdaa5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540117257048951%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=e72tuh7UTi8s66MwGF2JxAj1VyH5LLpsMgVpq5gURB0%3D&reserved=0> 体验可能会更好一些。唯一缺点是无法硬解视频。

**Comment by hmsjy2017** [comment]
Windows 10 ARM64 已经支持 x64 模拟了，效率竟然比模拟 x86 都高。

**Comment by aiminickwong** [comment]
> HDMI和3.5输出均只能输出单声道怎么办，是哪里设置的不对吗？

See [here](https://github.com/openfans-community-offical/Debian-Pi-Aarch64/blob/master/README.md#3-167-change-audio-mono-output-to-stereo-for-desktop-version-system).
