### ISSUE TITLE
how can i install the kernel header？

### ISSUE THREAD

**Issue by bbllmaster** [openfans-community-offical/Debian-Pi-Aarch64#177]
how can i install the kernel header？

**Comment by aiminickwong** [comment]
@bbllmaster 
See here: [https://github.com/openfans-community-offical/Debian-Pi-Aarch64/issues/160#issuecomment-759943610](https://github.com/openfans-community-offical/Debian-Pi-Aarch64/issues/160#issuecomment-759943610)
