### ISSUE TITLE
更新2021年4月11日内核，容器重启内核死机

### ISSUE THREAD

**Issue by lixiaoyu0123** [openfans-community-offical/Debian-Pi-Aarch64#179]
升级2021年4月11日内核之后
通过cecos重启容器，直接内核司机。稳定复现

**Comment by aiminickwong** [comment]
any more logs?

**Comment by aiminickwong** [comment]
We had testing in 

```
root@raspbian:~# uname -r
5.10.27-Release-OPENFANS+20210411-v8
```

No problems as your sad.

The better way give us more logs is better.

**Comment by lixiaoyu0123** [comment]
我有5个 容器在cecos中
我的操作路径是， 选中5个容器全部选中，然后执行重启。 内核死机。
单个重启没问题，只要全部选择，一起重启就出现了问题
