### ISSUE TITLE
suggestion: disable/remove resolvconf+dhcpcd by default in desktop edition

### ISSUE THREAD

**Issue by edxi** [openfans-community-offical/Debian-Pi-Aarch64#180]
I think that users who need to use the desktop environment will config wifi through the network-manager applet, on the desktop toolbar in most cases. In this case, dhcpcd will still configure an ip+route, and resolvconf will add a nameserver to resolv.conf, both are really not neccesary.

for example, I need to configure a static ip  192.168.1.2 as my default gateway through network-manager.  But since there is a dhcp server on my network, I will still get a dhcp assigned route 192.168.1.1.

I know I can configure /boot/interface as a workaround. 
Since the desktop edition uses network-manager to manage the network, it is possible to delete dhcpcd and resolvconf to prevent users from encountering the situation like me...
Just a suggestion, of course you can also indicate it in the document. Thanks

**Comment by aiminickwong** [comment]
That's a good answer, make to the issue Top 1st.
