### ISSUE TITLE
can this os running kodi and control by cec?

### ISSUE THREAD

**Issue by ihxperfect** [openfans-community-offical/Debian-Pi-Aarch64#182]
I installed kodi but can't set to autorun and can not control kodi by cec.
ps:my tv support cec.

**Comment by aiminickwong** [comment]
check the kernel mod and test, also open config in config.txt

**Comment by ihxperfect** [comment]
sorry buy is this a kernel mod ?
Linux raspbian 5.10.33-Release-OPENFANS+20210502-v8 #1 SMP PREEMPT Sun May 2 17:19:42 CST 2021 aarch64 GNU/Linux

and if add a "hdmi_ignore_cec=0" to config.txt means open cec funtion?
