### ISSUE TITLE
Application install using apt cannot install the latest version

### ISSUE THREAD

**Issue by daddy-lin** [openfans-community-offical/Debian-Pi-Aarch64#183]
by use default apt source  `http://mirrors.ustc.edu.cn/debian`
```
❯ cat /etc/apt/sources.list
deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster main non-free contrib
deb http://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main
deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main non-free contrib
deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main non-free contrib
```
The application `fail2ban` has installed version of `0.10.2-2` but the latest version is `0.11.2-1` and mirrors site ([click here](https://mirrors.tuna.tsinghua.edu.cn/debian/pool/main/f/fail2ban/)) has the latest version source. 
```
❯ apt search fail2ban
Sorting... Done
Full Text Search... Done
fail2ban/stable,now 0.10.2-2.1 all [installed]
  ban hosts that cause multiple authentication errors
...
❯ sudo apt install fail2ban=0.11.2-1
[sudo] password for xxx:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '0.11.2-1' for 'fail2ban' was not found
```
CAN I use apt to install the latest version ? 

addations:
```
❯ uname -a
Linux raspbian 5.4.83-OPENFANS+20210102-v8 #1 SMP Sat Jan 2 21:52:54 CST 2021 aarch64 GNU/Linux
❯ apt -v
apt 1.8.2.2 (arm64)
```

**Comment by aiminickwong** [comment]
@daddy-lin 

Version **0.11.2-1** is newest, but  it's not belongs to **stable** version **buster**, see here: 
[https://packages.debian.org/search?keywords=fail2ban&searchon=names&suite=stable&section=all](https://packages.debian.org/search?keywords=fail2ban&searchon=names&suite=stable&section=all)

It's belongs to **unstale** or  **testing** version **bullseye** , see here [https://packages.debian.org/search?keywords=fail2ban&searchon=names&suite=testing&section=all](https://packages.debian.org/search?keywords=fail2ban&searchon=names&suite=testing&section=all)
