### ISSUE TITLE
How to enable hardware accelerated decoding in Chromium?

### ISSUE THREAD

**Issue by misaka19465** [openfans-community-offical/Debian-Pi-Aarch64#188]
If I disable the flag `enable-accelerated-video-decode`, it will use VpxVideoDecoder, and if I enable it, chromium will use FFmpegVideoDecoder. What should I do?

**Comment by aiminickwong** [comment]
FFmpegVideoDecoder is used hardware accelerated, what is your means?

**Comment by misaka19465** [comment]
FFmpegVideoDecoder is even slower than VpxVideoDecoder. *I'm using Chromium installed by `apt install chromium`*

**Comment by aiminickwong** [comment]
If like that as your said, maybe you should compile the chromium from source code by yourself.

**Comment by misaka19465** [comment]
Could you please offer me the pre-installed chromium? apt can't install that package.
