### ISSUE TITLE
How to run Android apps in Debian Pi?

### ISSUE THREAD

**Issue by misaka19465** [openfans-community-offical/Debian-Pi-Aarch64#189]
The kernel doesn't support Binder, so it is impossible(maybe?) to install Anbox, but the README showed running Android apps. How did it work?

**Comment by aiminickwong** [comment]
Our kernel support Binder, it had built in kernel not built as module, you should mount the binder fs and dev by yourself mannal.

**Comment by misaka19465** [comment]
I've done that, it works. By the way, could you please offer me the system image?

**Comment by aiminickwong** [comment]
Sorry, That's just for early testing inside, not ye now.
