### ISSUE TITLE
怎么卸载Diablo2？

### ISSUE THREAD

**Issue by v1ajeros** [openfans-community-offical/Debian-Pi-Aarch64#191]
谢谢openfans提供这个固件。

我想把Diablo2卸载。
在exagear下，执行wingcfg可以看到Diablo2，不过无法卸载。
在wine uninstaller上也没有显示Diablo2。
有什么方法能够卸载Diablo2？
请教下，感谢！

**Comment by aiminickwong** [comment]
Just delete the files.
