### ISSUE TITLE
图形桌面使用配置连接无线网络遇到的问题

### ISSUE THREAD

**Issue by Arrowarcher** [openfans-community-offical/Debian-Pi-Aarch64#192]
我使用的中文版的说明
执行
`systemctl disable NetworkManager`
`sed -i  \
's/sudo systemctl restart NetworkManager/## sudo systemctl restart NetworkManager/g' \
/home/pi/.xsessionrc`
后，重启之后发现NetworkManager不会启动，需要我切换到root手动启动它
systemctl start NetworkManager
每次开机都会这样。

我不知道是怎么问题，请问如何解决呢

另外我发现英文版的命令和中文版的不一样
英文版的是
`systemctl network Manager`
中文版的是
`systemctl disable NetworkManager`

**Comment by aiminickwong** [comment]
TKS for report this issue, we had fix it.
The command "*systemctl network Manager*" was **not** right, 
it should be "**systemctl disable NetworkManager**", so the Chinese was right.
