### ISSUE TITLE
The path of "sysctl.conf" is wrong in README_zh.md

### ISSUE THREAD

**Issue by xflcx1991** [openfans-community-offical/Debian-Pi-Aarch64#193]
In section of "How to turn off TCP BBR".The original text is

> Edit the "/mnt/etc/sysctl.conf" file, execute the command "sysctl -p" to view the results, and do not see the following comments, representing the operation succeeded.

But the real path is `/etc/sysctl.conf`, is it a just typo?The same problem is also exist on Chinese translation.

**Comment by aiminickwong** [comment]
Fixed, THK for report.
