### ISSUE TITLE
 SSL certificate problem: self signed certificate when open web page at port 8443/9090

### ISSUE THREAD

**Issue by Daoctor** [openfans-community-offical/Debian-Pi-Aarch64#194]
<img width="509" alt="ssl error 09 33 44" src="https://user-images.githubusercontent.com/6562597/120947993-ba8e8180-c773-11eb-8fbd-b39ed128a977.png">

can't open https://host:9090 because of ssl error
i already try to use `Chrome` or `Edge` even `curl`, give me same error

**Comment by aiminickwong** [comment]
See [Here](https://medium.com/@idomo/chrome-bypassing-ssl-certificate-check-2-f8eb6c2be68a) to find a way to visit the web.
