### ISSUE TITLE
Kernel config

### ISSUE THREAD

**Issue by a279437145** [openfans-community-offical/Debian-Pi-Aarch64#200]
This system is pretty good.
I want to compile a kernel and install it on this system,but there is no config.gz in /proc .I tried the default .config but it seems that many features are lacking. May you send me the kernel config file.
5.10.42-Release-OPENFANS+20210611-v8

**Comment by aiminickwong** [comment]
I'm very sorry to can't improve you issue, but I hadn't any config files not yet now.
