### ISSUE TITLE
kex_exchange_identification: read: Connection reset by peer

### ISSUE THREAD

**Issue by evenlee** [openfans-community-offical/Debian-Pi-Aarch64#207]
Hi There

I tried 2021-06-11-OPENFANS-Debian-Buster-Desktop-Aarch64-ext4-v2021-2.0-U6-Release.img.xz on my pi 4, and I do not have a monitor attached, when I try to ssh to the server, i got the error in the title, and I flashed my sd card twice, still got same error,

When I tried to https:// ip.of.pi.4:9090, got and cannot find link page, please help, thanks.

**Comment by aiminickwong** [comment]
What's you ssh client?

**Comment by aiminickwong** [comment]
It's seems maybe you ip or network is not normally.

**Comment by evenlee** [comment]
Thanks aiminic, I used both terminal and iterm on my mac, they have save issue, I can see the assigned ip in my router, and ping command works. my router uses 10.0.0.1/24 as ip address.

**Comment by aiminickwong** [comment]
Would you please provide the size of the SD card and the model of the PI?

**Comment by evenlee** [comment]
I am using Raspberry Pi 4 Model B Rev 1.1(4GB RAM) with 32GB SD card.

**Comment by evenlee** [comment]
still not got the root cause, but got a workaround. I used respberry PI OS, and got same error. then I attached a monitor, and enabled the ssh by ui, and it works.
