### ISSUE TITLE
建议把README.md里的内容移到wiki里

### ISSUE THREAD

**Issue by CNflysky** [openfans-community-offical/Debian-Pi-Aarch64#21]
README.md内容太长了，不方便使用者检索,移到wiki里就好了。
另外资瓷你们做64位系统，加油

**Comment by aiminickwong** [comment]
@CNflysky 谢谢你的反馈，这里只是我们内部的项目仓库，详细的内容后期请访问 http://www.pifan.org 来获取帮助和支持，谢谢
