### ISSUE TITLE
How to install Deepin desktop or macOS Mojave on the BaseOS/BaseOS Plus++?

### ISSUE THREAD

**Issue by XiegqRs** [openfans-community-offical/Debian-Pi-Aarch64#211]
I have installed the base system, but now I want to install a desktop.
Thanks!

**Comment by aiminickwong** [comment]
1. BaseOS/BaseOS Plus++ are not support installed the macOS Mojave Desktop ENV , cuz macOS Mojave ENV is customed by us just for macOS Mojave Desktop ENV edtion only, If U wanna used macOS Mojave Desktop ENV, the best way is download and install macOS Mojave Desktop ENV edtion img directly.

2. We're not supported any Deepin or UOS things anymore, and it will **NEVER** in our plan, very sorry to this.
