### ISSUE TITLE
Read-only filesystem

### ISSUE THREAD

**Issue by nicholas-zww** [openfans-community-offical/Debian-Pi-Aarch64#214]
### Discussed in https://github.com/openfans-community-offical/Debian-Pi-Aarch64/discussions/213

<div type='discussions-op-text'>

<sup>Originally posted by **nicholas-zww** November 22, 2021</sup>
how to make a read-only file system? </div>

**Comment by aiminickwong** [comment]
mount or edit fstab with ro option. (ro, means read-only).

**Comment by aiminickwong** [comment]
mount or edit fstab with ro option. (ro, means read-only).

**Comment by nicholas-zww** [comment]
if the partition is mounted as read-only. We cannot write/save anything. What I am asking is something like file-system overlay, meaning that I will still save and modify the files, but of course, all changes wont be saved after reboot.

**Comment by aiminickwong** [comment]
An easy way is use a  script control ro/rw, and the specific directory for writeable choose a separate partition mount is better.
