### ISSUE TITLE
5.10.82-Release-OPENFANS+20211202-v8版本无法重启或者关机

### ISSUE THREAD

**Issue by hao86** [openfans-community-offical/Debian-Pi-Aarch64#215]
升级到5.10.82-Release-OPENFANS+20211202-v8以后，reboot和halt命令失效

**Comment by aiminickwong** [comment]
Pls add the system version and Pi version note and log or pic.

**Comment by aiminickwong** [comment]
Or you can try version "5.10.82-Release-OPENFANS+20211204-v8".
