### ISSUE TITLE
Upgrade link has not been valid yet

### ISSUE THREAD

**Issue by LouisYZK** [openfans-community-offical/Debian-Pi-Aarch64#217]
I find that there's no `raspistill` in `/opt/vc64/bin`, and noticed that it has been supported in Version Update Log;
Then i try to upgrade os version and related softwares, maybe the link of BaiduPan in '升级系统固件及驱动' has not been valid yet.

**Comment by aiminickwong** [comment]
**raspistill** is not from os and software upgrade, it's from out FW.
