### ISSUE TITLE
Wifi Module doesn't work

### ISSUE THREAD

**Issue by De3mond** [openfans-community-offical/Debian-Pi-Aarch64#219]
Raspberry 3 Model B, use Raspbian os wifi works, use the  latest debian os, wifi can't work.  /etc/wpa_supplicant/wpa_supplicant.conf is edited correctly.

**Comment by aiminickwong** [comment]
logs, versions, kernels, not latest.

**Comment by aiminickwong** [comment]
The available information is incomplete, cannot be followed up, pre-closed, please check in at any time. :) @De3mond
