### ISSUE TITLE
是否能够提供下Debian-Pi-Aarch64的交叉编译环境？

### ISSUE THREAD

**Issue by ferris001** [openfans-community-offical/Debian-Pi-Aarch64#22]
希望建立一个交叉编译环境，不知道如何获得Debian-Pi-Aaderch64的各种系统build依赖文件。
请问能否提供相应的交叉编译环境？

**Comment by aiminickwong** [comment]
@ferris001 系统主体涉及的是标准的aarch64 gcc交叉编译环境，整体的打包编译集成环境是在我们内部交叉编译系统上自动完成的，非开源，抱歉无法提供，再次感谢您的关注，谢谢。
