### ISSUE TITLE
[Advice]Could you upgrade glibc?

### ISSUE THREAD

**Issue by 123ABCDF11345** [openfans-community-offical/Debian-Pi-Aarch64#220]
the version of glibc of the latest OS is 2.28-10.However,the "sqlite3"module in npm need 2.29+.And I guess you know,it's an important module of all electron app.I tried to upgrade glibc from some article on Internet,however,I failed every time,and the system even can't work normally after I built and install it.
So could you update the glibc?The latest version is 2.32.Or can you give me some help for upgrade it by myself?
Ps. I tried to upgrade it by [this article](https://stackoverflow.com/questions/10863613/how-to-upgrade-glibc-from-version-2-13-to-2-15-on-debian)but I just see some error in package dependency issues.I also tried by [this one](https://stackoverflow.com/questions/35616650/how-to-upgrade-glibc-from-version-2-12-to-2-14-on-centos),but after I run 'make install',the system didn't work anymore.

Thanks for your help

**Comment by aiminickwong** [comment]
Version 2.29+ is not supported Debian Buster, the newer edition will be soon this year as Debian bullseye edition.
Thanks.
