### ISSUE TITLE
Are there any plans to upgrade to Debian 11 (Bullseye) ?

### ISSUE THREAD

**Issue by GoingTime** [openfans-community-offical/Debian-Pi-Aarch64#221]
Debian 11 has some exciting improvements to filesystems, printers, and more.

**Comment by aiminickwong** [comment]
Yes! The newer edition will be soon this year as Debian bullseye edition.

**Comment by GoingTime** [comment]
Thank you for your reply. I wonder if there are any plans to replace Docker with Podman ？
