### ISSUE TITLE
pi4 4g 问题

### ISSUE THREAD

**Issue by zerofo** [openfans-community-offical/Debian-Pi-Aarch64#23]
2019-08-16-OPENFANS-Deepin-Professional-Desktop-Aarch64-ext4-v2019-2.0-RC2.img
使用官方电源，经常跳电。 官方镜像没出现这个问题。

卡登入。 画面错开 无法进入
![微信图片_20190819135505](https://user-images.githubusercontent.com/46804648/63242150-fa2b6700-c288-11e9-8460-0c2c1dda218e.jpg)

**Comment by aiminickwong** [comment]
检查你的TF卡及HDMI接口，此问题非系统问题。
另外请参考TF要求，公众号及管网教程补充说明已更新
