### ISSUE TITLE
树莓派4双屏显示不支持

### ISSUE THREAD

**Issue by thkzoro** [openfans-community-offical/Debian-Pi-Aarch64#24]
在树莓派4安装2.0的deepin后，想体验一下双屏显示，发现并不支持，如何才能使用双屏功能呀？

**Comment by aiminickwong** [comment]
@thkzoro   抱歉，我们还未在双屏上做测试，无法给您准确的答复，您可以参考官方的设置尝试，期待您的反馈。

**Comment by aiminickwong** [comment]
Cuz there is no feedback for a long time, closed it now, any time who wanna, please request open again.
