### ISSUE TITLE
For raspi 3b, there's a end trace panic.

### ISSUE THREAD

**Issue by victoryang00** [openfans-community-offical/Debian-Pi-Aarch64#25]
Firstly as the doc said, it should boot again twice to get into the rootfs done. But unfortunately, in raspi 3b, it gets into end trace panic.
I've modified the config.txt into 
> device_tree=bcm2710-rpi-3-b.dtb
but it still doesn't show up the system.

**Comment by aiminickwong** [comment]
check you IMG md5, and re-build system TF cards.
