### ISSUE TITLE
缺少安装过程的文档

### ISSUE THREAD

**Issue by hughjfchen** [openfans-community-offical/Debian-Pi-Aarch64#28]
首先，这是我见到文档比较全的中文项目了。
不过看了repo中所有的文档，没有提到如何安装的。对于安装过程，目前可以找到的文档有以下内容：
1.image列表及内容说明
2.image的对比及推荐选择
3.第一次启动的说明

但没有以下内容：
1.需要下载哪些文件？image肯定要选择一种下载，但还有内核固件要不要下载？没有说明
2.下载后如何刻录？
希望能补充一下以上内容。

**Comment by aiminickwong** [comment]
树莓派的基础镜像烧录方式都一样，这里是项目文档，没有公开宣传，你的其他问题请访问树莓派基地官网寻求技术支持，我们也有说明技术支持由树莓派官方提供，本项目GIT仅供仓库存放使用，谢谢关注。@hughjfchen

**Comment by hughjfchen** [comment]
我知道如何下载刻录基础镜像，但内核固件又是如何用的呢？我找了树莓派的网站没发现。

**Comment by aiminickwong** [comment]
@hughjfchen  所有树莓派的镜像使用方法都一样，这个跟我们系统无关。
