### ISSUE TITLE
（4B）CPU超频问题

### ISSUE THREAD

**Issue by lifeorwar** [openfans-community-offical/Debian-Pi-Aarch64#32]
改了参数就不亮机了，要通过什么方式实现呀

**Comment by aiminickwong** [comment]
这里不讨论超频问题，请到基地官网论坛提问了，谢谢合作。@lifeorwar

**Comment by PatrickChina** [comment]
raspberry pi 4B firmware limited the CPU clock under 2.0GHZ and over voltage under 8. Any thing higher than that could lead to a failure on boot up.
Up to now unless you change the board circuit or develop your own firmware. There is no way to get your clock over 2.0
