### ISSUE TITLE
Network Manager Wait Online 【err】

### ISSUE THREAD

**Issue by phynex** [openfans-community-offical/Debian-Pi-Aarch64#33]
原来是0816 web++版本，64G内存卡 ，新刷内存卡启动的时候都会提示Network Manager Wait Online 【err】,今天更换了256G内存卡，重新刷，0903版本 ，还是提示同样错误，树莓派4B   4G版本 ，千兆有线连接。进入web，Network Manager 服务 没有启动，而且无法启动，
![Snipaste_2019-09-05_14-38-51](https://user-images.githubusercontent.com/7844681/64396843-94651a80-d091-11e9-9769-c41f97338420.jpg)

**Comment by aiminickwong** [comment]
不按照教程设置网络就会有错误

**Comment by aiminickwong** [comment]
提供的具体情况也不明，无效的问题反馈
