### ISSUE TITLE
镜像下载太慢了，建议用sync同步

### ISSUE THREAD

**Issue by xujipm** [openfans-community-offical/Debian-Pi-Aarch64#34]
这里是介绍，有免费版本的，用这个可以大大提升下载速度
https://www.resilio.com/individuals/

百度的下载速度，直接吓走了一部分爱好者，我都不晓得该怎么下载，下载到一般提示失败，百度云盘太恶心了

可以在系统内置这个软件，默认同步最新的release，用户安装完系统后可以选择关闭这个同步

**Comment by aiminickwong** [comment]
暂时没有计划
