### ISSUE TITLE
内核源码对应在哪里呢？需要内核头文件编译驱动

### ISSUE THREAD

**Issue by fml927** [openfans-community-offical/Debian-Pi-Aarch64#36]
哪里可以下载内核源码或头文件，需要编译驱动

**Comment by aiminickwong** [comment]
@fml927 https://github.com/raspberrypi/linux

**Comment by fml927** [comment]
咱们这个 OPENFANS Debian Pi Aarch64 系统没有对raspbrrypi原生系统内核进行修改么？

**Comment by fml927** [comment]
想基于RC5开发驱动。
RC5基于哪个版本的 raspberry pi版本呢？  没查到相关信息。
还是随便用一个raspberrypi内核替换也能工作呢？

**Comment by aiminickwong** [comment]
@fml927 目前我们的内核还是4.19 RC5有对应的内核版本啊 uname-r可以看到

**Comment by fml927** [comment]
ok  Thanks~
