### ISSUE TITLE
下载链接就不能改成其他的吗？

### ISSUE THREAD

**Issue by 1759749908** [openfans-community-offical/Debian-Pi-Aarch64#40]
我的百度网盘被限制速度了，而你们提供的下载链接也只有百度网盘能使用。哪怕是P2P也好，能不能不要让我使用这个恶心的百度网盘了？

**Comment by aiminickwong** [comment]
@1759749908  HUAWEI的是你自己不会用

**Comment by 1759749908** [comment]
那个HUAWE的链接打开后就是一堆XML代码，还提示This XML file does not appear to have any style information associated with it. The document tree is shown below.

**Comment by lt-fancy** [comment]
one drive和google drive下载速度贼快
