### ISSUE TITLE
3-10macos_mojave主题桌面安装vnc远程 应该进行修改

### ISSUE THREAD

**Issue by 1759749908** [openfans-community-offical/Debian-Pi-Aarch64#42]
“3-10macos_mojave主题桌面安装vnc远程”
`cd ~ ; wget https://www.realvnc.com/download/file/vnc.files/VNC-Server-6.5.0-Linux-ARM.deb`
`apt install ./VNC-Server-6.5.0-Linux-ARM.deb`
这2个地方应该把6.5.0修改为目前最新的6.6.0

`rm -rf ./VNC-Server-6.4.0-Linux-ARM.deb`
这里的6.4.0也应该修改为6.6.0。
指令中的“-rf”也没有必要添加上去。

还有：下载了“VNC-Server-6.5.0-Linux-ARM.deb”，最后把“VNC-Server-6.4.0-Linux-ARM.deb”删掉了是什么操作？？？

**Comment by aiminickwong** [comment]
@1759749908 谢谢反馈，因为包已经安装了，不再需要就可以吧安装包删除，当然也可以留着

**Comment by aiminickwong** [comment]
@1759749908 已修正，再次感谢。
