### ISSUE TITLE
能否构建一个“纯净”版镜像，就像官方的三个版本？

### ISSUE THREAD

**Issue by equiclouds** [openfans-community-offical/Debian-Pi-Aarch64#43]
非常有意义的工作，树莓派官方并没有出64位系统的计划。
我找64位可在树莓上稳定运行的系统很长时间了，这个镜像真是犀利！！！但感觉镜像里面集成的东西太多了，能否出个就像官方的系统一样纯净的系统，不需要宝塔等那些第三方软件的纯净版系统，包括Docker也可以自行安装。

Raspbian Buster with desktop and recommended software
Image with desktop and recommended software based on Debian Buster

Raspbian Buster with desktop
Image with desktop based on Debian Buster

Raspbian Buster Lite

**Comment by aiminickwong** [comment]
目前基础版就是比较干净了，只是预装了docker而已，不喜欢可以自行删除。
