### ISSUE TITLE
VNC 

### ISSUE THREAD

**Issue by Rehtt** [openfans-community-offical/Debian-Pi-Aarch64#58]
run `sudo dpkg --remove-architecture armhf`
result `dpkg: error: cannot remove architecture 'armhf' currently in use by the database`
raspberry 3b

**Comment by aiminickwong** [comment]
@Rehtt You had installed some armhf pkgs, run **`dpkg -l  | grep armhf`** to check them first, then used  **`dpkg --purge  xxxx`** (the armhf pkg your checked) to remove all pkgs your checked , after this and run **`dpkg --remove-architecture armhf`** again.
