### ISSUE TITLE
Customising locale?

### ISSUE THREAD

**Issue by puccaso** [openfans-community-offical/Debian-Pi-Aarch64#59]
awesome work, really! =]=]

how can we start to customise the locale? i don't read mandarin :/

**Comment by aiminickwong** [comment]
@puccaso  The system default language is `en_US`, but under the `desktop_env` user pi's `lang_env` had set to `zh_CN` in `/home/pi/.xsessionrc`  file, to change the pi's `lang_env` you can edit this file and reboot.

**Comment by aiminickwong** [comment]
Since there is no further feedback on this issue, we will close it and reopen it at any time if there is any need to update it.

**Comment by CippoD2** [comment]
After this precious information i can say that's this is the best distro for my Raspberry pi 3 b+ (in my opinion).
Thank you very much for your **GREAT** work.
