### ISSUE TITLE
命令行下应该如何配置多个wifi呢？

### ISSUE THREAD

**Issue by jn3393** [openfans-community-offical/Debian-Pi-Aarch64#6]
我安装的是无桌面版的，请问：链接一个WiFi我会配置，在boot/wlan0里直接配置账号和密码即可，但是我想设置保存多个wifi并自动连接。比如到家里自动连接家里wifi，到公司直接连接公司wifi该如何配置呢。

**Comment by aiminickwong** [comment]
Use a network card alias, like wlan0:1 , configure wlan0:1 like wlan0, enjoy.
@jn3393

**Comment by jn3393** [comment]
Thx
