### ISSUE TITLE
How to use spi？

### ISSUE THREAD

**Issue by qingshutie** [openfans-community-offical/Debian-Pi-Aarch64#60]

**Comment by aiminickwong** [comment]
@qingshutie  Edit the `/boot/config.txt` file, add `dtparam=spi=on`  and reboot.
Then you can find the SPI device `/dev/spidev0.0`

C Test:

```
#Shell
# Write binary 1, 2 and 3
echo -ne "\x01\x02\x03" > /dev/spidev0.0
```

**Comment by aiminickwong** [comment]
Since there is no further feedback on this issue, we will close it and reopen it at any time if there is any need to update it.
