### ISSUE TITLE
Won't working on my 4B

### ISSUE THREAD

**Issue by lt-fancy** [openfans-community-offical/Debian-Pi-Aarch64#61]
2019-11-17-OPENFANS-Debian-Buster-Aarch64-ext4-v2019-2.0-Release-plus++.img

Not working on my 4B, but perfectly worked on my 3B.

**Comment by aiminickwong** [comment]
Check your emmc card socket.
You didn't provide any useful information to locate the issue.
This isn't a good way to submit the issue.
