### ISSUE TITLE
Some errors in Raspberry 3B+

### ISSUE THREAD

**Issue by walcer** [openfans-community-offical/Debian-Pi-Aarch64#63]
I have installed the latest version image in my Raspberry 3B+, and access the web-gui managment successful. When I read the logs  in web-gui and found some serious errors. The logs can't be copy into a text file, so I will paste it in photo. Now, I have a query should I deal those errors log?
![error1](https://user-images.githubusercontent.com/23720899/69509348-9beede00-0f73-11ea-8820-092304bbb473.png)
![error2](https://user-images.githubusercontent.com/23720899/69508157-db1b3000-0f6f-11ea-82f0-13fd9a63d46c.png)

**Comment by aiminickwong** [comment]
@walcer   Thanks for you report, it doesn't matter, be ignored.
