### ISSUE TITLE
how can i enable watchdog?

### ISSUE THREAD

**Issue by wenco** [openfans-community-offical/Debian-Pi-Aarch64#67]
dear,when i vi /etc/modules add bcm2708_wdog, enable it but failed.it not found this modules. so, how can i use it?

**Comment by aiminickwong** [comment]
Used `dmesg` command, you will see the watchdog was enabled.

bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer

**Comment by wenco** [comment]
thanks!
