### ISSUE TITLE
Is it possible to open source the kernel code

### ISSUE THREAD

**Issue by ldseraph** [openfans-community-offical/Debian-Pi-Aarch64#68]
hello openfans
I am debugging Bluetooth mesh. so need to recompile the kernel in order to open some driver module.
CONFIG_CRYPTO_CMAC=y
CONFIG_CRYPTO_USER_API=y
CONFIG_CRYPTO_USER_API_HASH=y
CONFIG_CRYPTO_USER_API_SKCIPHER=y
CONFIG_DYNAMIC_DEBUG=y

**Comment by aiminickwong** [comment]
You can choose the Raspberry Pi official source code.
We use the same code as the official, except for the custom part.
