### ISSUE TITLE
complie protobuf3

### ISSUE THREAD

**Issue by coltzwz** [openfans-community-offical/Debian-Pi-Aarch64#69]
when i compile protobuf3, it can't complete. compile log:
`
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_65ca7.dir/link.txt --verbose=1
    /usr/bin/cc      -rdynamic CMakeFiles/cmTC_65ca7.dir/testCCompiler.c.o  -o cmTC_65ca7 
    /usr/bin/ld: cannot find Scrt1.o: No such file or directory
    /usr/bin/ld: cannot find crti.o: No such file or directory
    /usr/bin/ld: cannot find -lc
    /usr/bin/ld: cannot find crtn.o: No such file or directory
`

**Comment by aiminickwong** [comment]
This is not a system issue.
Here: https://askubuntu.com/questions/251978/cannot-find-crti-o-no-such-file-or-directory
May be can help you.
