### ISSUE TITLE
Qemu running aarch64 win10 has ramfb problem

### ISSUE THREAD

**Issue by zengold** [openfans-community-offical/Debian-Pi-Aarch64#70]
running Qemu CLI：
sudo qemu-system-aarch64  \
-M virt-2.12 \
-smp 2 \
-m 1.5G \
-cpu host \
-enable-kvm \
-bios QEMU_EFI.img \
-vga none \
-device ramfb \
-device ich9-usb-ehci1 \
-device usb-kbd \
-device usb-mouse \
-device usb-tablet \
-device usb-storage,drive=install \
-drive if=none,id=install,format=raw,media=cdrom,file=18362.387.190923-1719.19H1_RELEASE_SVC_PROD3_CLIENTPRO_OEMRET_A64FRE_ZH-CN.ISO \
-device usb-storage,drive=drivers \
-drive if=none,id=drivers,media=cdrom,file=drivers.vhdx \
-device virtio-net,netdev=net0 \
-netdev user,id=net0,hostfwd=tcp::5555-:3389 \
-hda system.vhdx

appear problem：
Could not open option rom 'vgabios-ramfb.bin': No such file or directory
gtk initialization failed

**Comment by aiminickwong** [comment]
It's already show you haven't vgabios-ramfb.bin and another way the windows 10 arm has not been officially supported by Qemu, and we are still developing it by ourself.
