### ISSUE TITLE
这个要怎么安装至移动硬盘？

### ISSUE THREAD

**Issue by woyuchengfengerqu** [openfans-community-offical/Debian-Pi-Aarch64#76]
如题！！！我百度过了，修改root=partuuid=....-02试过了，都好像不行，Google不好上。。。

**Comment by aiminickwong** [comment]
Can you talk with EN ?

**Comment by woyuchengfengerqu** [comment]
I can't speak English. ╮(╯▽╰)╭
I want to install the system into the mobile hard disk.

                                                              --From Baidu translation
