### ISSUE TITLE
5ghz wifi don't work on rpi4

### ISSUE THREAD

**Issue by MarcoPower01** [openfans-community-offical/Debian-Pi-Aarch64#79]
My 5ghz wifi don't work i have tried different channels and modem but didn't work.

**Comment by aiminickwong** [comment]
Your need to change your wifi region.

**Comment by MarcoPower01** [comment]
How can I change it
Because when I type "iw reg set IT"
And I check the "iw reg get" is IT
After reboot it return to "CN" again

**Comment by MarcoPower01** [comment]
Problem solved just change the region in /etc/default/crda
