### ISSUE TITLE
how to remove the welcome msg when I ssh in pi? 

### ISSUE THREAD

**Issue by alango0820** [openfans-community-offical/Debian-Pi-Aarch64#80]
I dont want the pi to show this message every I ssh into it.how to remove it? 

  .~~.   .~~.         ___                __                      ___  _ 
   '. \ ' ' / .'      / _ \___  ___ ___  / /  ___  ___ ___ _ __  / _ \(_)
    .~ .~~~..~.      / , _/ _ `(_-</ _ \/ _ \/ -_) __/ __/ // / / ___/ / 
   : .~.'~'.~. :    /_/|_|\_,_/___/ .__/_.__/\__/_/ /_/  \_, / /_/  /_/  
  ~ (   ) (   ) ~                /_/                    /___/          
 ( : '~'.~.'~' : )  
  ~ .~ (   ) ~. ~     Copyright (c) 2017-2020, OPENFANS.ORG & PIFAN.ORG
   (  : '~' :  )      Linux Version 4.19.83-OPENFANS+20191116-v8
    '~ .~~~. ~'       Compiled #1 SMP PREEMPT Sat Nov 16 23:32:48 CST 2019
        '~'           Four ARM  Processors, 3.9GB RAM
                      432.00 Bogomips Total

**Comment by aiminickwong** [comment]
We do not recommend this.
