### ISSUE TITLE
How to config HardFP for ffmpeg

### ISSUE THREAD

**Issue by yeachen1990** [openfans-community-offical/Debian-Pi-Aarch64#81]
Hi
I have a pi4 ，I want compile ffmpeg in pi 4,But it doesn't seem to support MMAL，I enabled VChardfp,How do I set up ffmpeg support hardware acceleration?
Which command line should I add to the ffmpeg config？

**Comment by aiminickwong** [comment]
Our default desktop version had  supported ffmpeg hardware acceleration.

**Comment by yeachen1990** [comment]
if I use BaseOS Plus++ image,How to support ffmpeg hardware acceleration.

**Comment by aiminickwong** [comment]
The baseos not include  ffmpeg pkg, we just add the ffmpeg pkg in desktop edition.
