### ISSUE TITLE
In the launcher search bar the backspace doesn't work

### ISSUE THREAD

**Issue by MarcoPower01** [openfans-community-offical/Debian-Pi-Aarch64#85]
if you click the backspace in the launcher search bar it will write this:  ÿ

i changed the system locale (.xsessionrc) and the keyboard language
system locale: it_IT 
keyboard language:  Italian

**Comment by aiminickwong** [comment]
Any debug logs or msg?

**Comment by aiminickwong** [comment]
No feedback for a long time, close the question, welcome to update and ask to open at any time. :)
