### ISSUE TITLE
/usr/bin/ld: cannot find -lbrcmGLESv2

### ISSUE THREAD

**Issue by Jyurineko** [openfans-community-offical/Debian-Pi-Aarch64#88]
when  i compile my project
`root@raspbian:~/ceshi# gcc -I/opt/vc/include -c main.c -o main.o`
`root@raspbian:~/ceshi# gcc -L/opt/vc/lib main.o -lbrcmGLESv2 -lbrcmEGL -o main`
 it shows: `/usr/bin/ld: cannot find -lbrcmGLESv2 `

**Comment by aiminickwong** [comment]
That's rpi offical support.
