### ISSUE TITLE
2月13号的xfce桌面版系统boot不了

### ISSUE THREAD

**Issue by xiezhuojin** [openfans-community-offical/Debian-Pi-Aarch64#9]

**Comment by aiminickwong** [comment]
...
Any info???? @xiezhuojin

**Comment by aiminickwong** [comment]
Check your img's md5 and shasum.

**Comment by xiezhuojin** [comment]
md5是对的，
![screen shot 2019-02-21 at 18 20 06](https://user-images.githubusercontent.com/37146118/53167584-4582f680-3613-11e9-894f-fa252d3b339b.png)，就是在安装重启一直卡着

**Comment by aiminickwong** [comment]
卡在那一步了？

**Comment by aiminickwong** [comment]
@xiezhuojin Please use the newest version: U8, and TF card to boot your system.
