### ISSUE TITLE
how can I run 32bit ffmpeg or 64bit userland enable ffmpeg with h264_omx and h264_mmal?

### ISSUE THREAD

**Issue by letmejoin** [openfans-community-offical/Debian-Pi-Aarch64#91]
Because part of userland doesn't support 64bit arm, especially OpenMax IL(h264_omx), and MMAL run with error in my mashine, ffmpeg hw codec/decode.
But 32bit ffmpeg run correctly with both h264_mmal and h264_omx, so whether there are some methods run 32bit ffmpeg in arm64 or offering a  complete 64bit userland: https://github.com/raspberrypi/userland

Very thanks for your contribution！！！

**Comment by aiminickwong** [comment]
Same Qustion as #91, close
