### ISSUE TITLE
nfs挂载时出现mount.nfs: mount system call failed

### ISSUE THREAD

**Issue by 2lifetop** [openfans-community-offical/Debian-Pi-Aarch64#93]
利用网页挂载和使用如下命令都会出现如上问题
`mount -t nfs -o vers=3,nolock,rw remote_ip:remote_dir local_dir`

**Comment by aiminickwong** [comment]
Can you try it in command line env again?

**Comment by aiminickwong** [comment]
No feedback for a long time, close the question, welcome to update and ask to open at any time. :)
