### ISSUE TITLE
how to close it port 8000？

### ISSUE THREAD

**Issue by muxiaotk** [openfans-community-offical/Debian-Pi-Aarch64#98]
The  8000 port is open, what process is it, and how to close it？is look like be uesd by caas，so i look this “cecos-caas.service”
[Service]
User=root
ExecStart=/opt/cecos-caas/cecos-caas-armv8  --data="/opt/cecos-caas/data/"  --assets="/opt/cecos-caas/"  --template-file="/opt/cecos-caas/templates.json"  -H  unix:///var/run/docker.sock  --no-analytics  --ssl  --sslkey  /opt/cecos-caas/certs/caas.key  --sslcert  /opt/cecos-caas/certs/caas.crt  --bind=":8443"       
ExecReload=/bin/kill -HUP $MAINPID
just use port 8443？
默认的8000端口是打开的，如何只开8443？

**Comment by ExplodingFKL** [comment]
Same problem, unable to find the configuration file location.

**Comment by aiminickwong** [comment]
Stop this service
