### ISSUE TITLE
The new WPS client "WPS 2019" is ready!!!

### ISSUE THREAD

**Issue by 1759749908** [openfans-community-offical/Debian-Pi-Aarch64#99]
An exciting piece of news! Hope to add this new "WPS" client in the new system version!
Link:"https://linux.wps.cn/"
![截图_2020-02-07_16-39-05](https://user-images.githubusercontent.com/28804414/74014034-c96ef380-49c8-11ea-92b2-cae6a6793620.png)
![截图_2020-02-07_16-39-33](https://user-images.githubusercontent.com/28804414/74014046-cffd6b00-49c8-11ea-85a0-d63884e14a2a.png)
![截图_2020-02-07_16-40-13](https://user-images.githubusercontent.com/28804414/74014054-d2f85b80-49c8-11ea-8c7a-427407d0d99f.png)

**Comment by aiminickwong** [comment]
We had included, soon or later will be publish.
